from sqlite_database import *
from data import *

############ To Do: Deduct the power took from grid from credit available #########

#Checking for the power consumption at hour x during week
i = 0
for i in range(24):
    if totalSolarAvailable[i] > totalPowerConsumedWeek[i]:
        #We use power generated by the solar panel only
        restSolarPower = totalSolarAvailable[i] - totalPowerConsumedWeek[i]
        creditGeneratedWeek[i] = restSolarPower * powerCostWeek[i]
        energyToBuyWeek[i] = 0
        print("creditGenerated at ", i, "am is: ",  creditGeneratedWeek[i])
    else:
        creditGeneratedWeek[i] = 0
        powerToBuy = totalPowerConsumedWeek[i] - totalSolarAvailable[i]
        energyToBuyWeek[i] = powerToBuy * powerCostWeek[i]
        print("energyToBuy at ", i, "am is: ", energyToBuyWeek[i])

#Checking for the power consumption at hour x during weekend
i = 0
for i in range(24):
    if totalSolarAvailable[i] > totalPowerConsumedWeekend[i]:
        #We use power generated by the solar panel only
        restSolarPower = totalSolarAvailable[i] - totalPowerConsumedWeekend[i]
        creditGeneratedWeek[i] = restSolarPower * powerCostWeek[i]
        energyToBuyWeek[i] = 0
        #print("creditGenerated at ", i, "am is: ",  creditGeneratedWeek[i])
    else:
        #Use solar power available and buy rest from grid
        creditGeneratedWeek[i] = 0
        powerToBuy = totalPowerConsumedWeekend[i] - totalSolarAvailable[i]
        energyToBuyWeek[i] = powerToBuy * powerCostWeek[i]
        #print("energyToBuy at ", i, "am is: ", energyToBuyWeek[i])

print("creditGeneratedWeek", creditGeneratedWeek)                                                                       #### For debug only
print("creditGeneratedWeekend", creditGeneratedWeekend)                                                                 #### For debug only
print("energyToBuyWeek", energyToBuyWeek)                                                                               #### For debug only
print("energyToBuyWeekend", energyToBuyWeekend)                                                                         #### For debug only
